#build
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline

COPY src ./src
# build the jar
RUN mvn -q -e -DskipTests package

# ---------- Runtime stage ----------
FROM eclipse-temurin:17-jre
WORKDIR /app

# (Optional) create non-root user for security
RUN useradd -ms /bin/bash spring
USER spring

# copy the fat jar from the build stage
COPY --from=build /app/target/*.jar app.jar

# Expose the HTTP port of Spring Boot
EXPOSE 8080

# Pass JVM opts via env var if needed
ENV JAVA_OPTS=""

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]